-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(T.TOTAL_SALES) AS TOTAL_SALES
    FROM BOOK B JOIN 
    (SELECT S.BOOK_ID, SUM(S.SALES) AS TOTAL_SALES
        FROM  BOOK_SALES S 
        WHERE S.SALES_DATE LIKE "2022-01%"
        GROUP BY S.BOOK_ID) T
    ON B.BOOK_ID = T.BOOK_ID
    GROUP BY CATEGORY
    ORDER BY B.CATEGORY;
